routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//cart
Route::get('add_to_cart/{id}',['uses'=>'ProductController@getAddToCart','as'=>'products.addToCart']);
Route::get('Padd_to_cart/{id}',['uses'=>'PurchaseController@getAddToCart','as'=>'purchase.addToCart']);
Route::get('shopping-cart',['uses'=>'ProductController@getCart','as'=>'products.shoppingCart']);
Route::get('/','PagesController@getIndex');
Route::get('showDesign', 'PagesController@showDesign');
Route::get('/reduce/{id}', ['uses' => 'ProductController@getReduceByOne','as' => 'product.reduceByOne']);
Route::get('/remove/{id}', ['uses' => 'ProductController@getRemoveItem','as' => 'product.remove']);
Route::get('empty','ProductController@empty')->name('clearCart');

Route::group(['middleware'=>['web','auth']],function(){
    //checkout
    Route::get('checkout',['uses'=>'ProductController@getCheckout', 'as'=>'checkout']);
    Route::post('checkout',['uses'=>'ProductController@postCheckout', 'as'=>'checkout']);
    //Pages Controller
    Route::get('contact', 'PagesController@getContact');
    Route::post('contact', 'PagesController@postContact');

    //resource controllers
    Route::resource('purchases','PurchaseController',['except'=>['edit','update']]);
    Route::resource('designs','DesignController',['except'=>['create','index','edit','update','show']]);
    Route::resource('products', 'ProductController',['except'=>['edit','update']]);
    Route::resource('categories', 'CategoryController');

    //ProfileController
    Route::get('/profile/{slug}','ProfileController@index')->name('profile.index');
    Route::get('/profile/edit/profile','ProfileController@edit')->name('profile.edit');
    Route::post('/profile/update','ProfileController@update')->name('profile.update');
    Route::get('/changeImage','ProfileController@changeImage');
    Route::post('/uploadImage','ProfileController@uploadImage');

    Route::get('/findFriends', 'ProfileController@findFriends');
    Route::get('/addFriend/{id}', 'ProfileController@sendRequest');
    Route::get('/followers', 'ProfileController@followers');
    Route::get('/unfollow/{id}', 'ProfileController@unfollow');
    Route::get('/notifications/{id}', 'ProfileController@notifications');

    //Route::get('/accept/{name}/{id}', 'ProfileController@accept');

    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
});

Auth::routes();

Route::get('/welcome', 'PagesController@getIndex')->name('welcome');

resources/views/contact.blade.php
@extends('main')

@section('title', '|contact')

@section('content')
        <div class="container">
            <div class="col-md-10 col-md-offset-1">
                <h1>contact Us</h1>
                <h6>Send A Mail To Our Admin</h6>
                <hr>
                <form action="{{ url('contact') }}" method="POST">
                    {{ csrf_field() }}
                    <div class="col-md-8 col-md-offset-2">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label for="email" name="message">Email:</label>
                                <input class="form-control" placeholder="your email" type="text" name="email" id="email">
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                <label for="subject" name="subject">Name:</label>
                                <input class="form-control" placeholder="input your Name" type="text" name="name" id="subject">
                            </div>
                        </div>
                        <div class="col-md-10">
                            <div class="form-group">
                                <label for="message" name="message">Message:</label>
                                {{ Form::textarea('message',null,['class'=>'form-control','id'=>'message']) }}
                            </div>
                            <input type="submit" value="submit" class="btn btn-success btn-sm">
                        </div>
                    </div>
                </form>
            </div>
        </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/main.blade.php
@include('partials._head')
    <body>
        @include('partials._nav')
        <div class="container">
            @include('partials._messages')
            @yield('content')

        </div>
            <div class="">
                <div class="copy-w3right">
            		<div class ="">
                        @if (Auth::check())
                            <div class="top-nav bottom-w3lnav">
                                <ul>
                                    <li><a href="{{ url('/') }}">Home</a></li>
                                    <li><a href="about.html">About</a></li>
                                    <li><a href="{{ url('showDesign') }}">Designs</a></li>
                                    <li><a href="{{ route('products.index') }}">Shop</a></li>
                                    <li><a href="typo.html">Typography</a></li>
                                    <li><a href="{{ url('contact') }}">Contact</a></li>
                                </ul>
                            </div>
                        @endif
            			<p align="center"> copyright Tailored 2017 </p>
            		</div>
            	</div>

            </div>
        @include('partials._scripts')
    </body>
</html>