routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//cart
Route::get('add_to_cart/{id}',['uses'=>'ProductController@getAddToCart','as'=>'products.addToCart']);
Route::get('Padd_to_cart/{id}',['uses'=>'PurchaseController@getAddToCart','as'=>'purchase.addToCart']);
Route::get('shopping-cart',['uses'=>'ProductController@getCart','as'=>'products.shoppingCart']);
Route::get('/','PagesController@getIndex');
Route::get('showDesign', 'PagesController@showDesign');
Route::get('/reduce/{id}', ['uses' => 'ProductController@getReduceByOne','as' => 'product.reduceByOne']);
Route::get('/remove/{id}', ['uses' => 'ProductController@getRemoveItem','as' => 'product.remove']);
Route::get('empty','ProductController@empty')->name('clearCart');

Route::group(['middleware'=>['web','auth']],function(){
    //checkout
    Route::get('checkout',['uses'=>'ProductController@getCheckout', 'as'=>'checkout']);
    Route::post('checkout',['uses'=>'ProductController@postCheckout', 'as'=>'checkout']);
    //Pages Controller
    Route::get('contact', 'PagesController@getContact');
    Route::post('contact', 'PagesController@postContact');

    //resource controllers
    Route::resource('purchases','PurchaseController',['except'=>['edit','update']]);
    Route::resource('designs','DesignController',['except'=>['create','index','edit','update','show']]);
    Route::resource('products', 'ProductController',['except'=>['edit','update']]);
    Route::resource('categories', 'CategoryController');

    //ProfileController
    Route::get('/profile/{slug}','ProfileController@index')->name('profile.index');
    Route::get('/profile/edit/profile','ProfileController@edit')->name('profile.edit');
    Route::post('/profile/update','ProfileController@update')->name('profile.update');
    Route::get('/changeImage','ProfileController@changeImage');
    Route::post('/uploadImage','ProfileController@uploadImage');

    Route::get('/findFriends', 'ProfileController@findFriends');
    Route::get('/addFriend/{id}', 'ProfileController@sendRequest');
    Route::get('/followers', 'ProfileController@followers');
    Route::get('/unfollow/{id}', 'ProfileController@unfollow');
    Route::get('/notifications/{id}', 'ProfileController@notifications');

    //Route::get('/accept/{name}/{id}', 'ProfileController@accept');

    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
});

Auth::routes();

Route::get('/welcome', 'PagesController@getIndex')->name('welcome');

resources/views/partials/_head.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Tailored @yield('title')</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="application/x-javascript"> addEventListener("load", function()
        { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
        <link href="//fonts.googleapis.com/css?family=Limelight" rel="stylesheet">
        <link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,
        400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
            <link rel="stylesheet" href="{{asset('css/app.css')}}">
            <link rel="stylesheet" href="{{asset('css/styles.css')}}">
            <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
            <link rel="stylesheet" href="{{asset('css/font-awesome.css')}}">
            <link href="{{asset('css/bootstrap.css')}}" type="text/css" rel="stylesheet" media="all">
            <link href="{{asset('css/style.css')}}" type="text/css" rel="stylesheet" media="all">
            <link rel="stylesheet" href="{{asset('css/w3.css')}}">
    </head>

resources/views/partials/_messages.blade.php
@if (Session::has('success'))

    <div class="alert alert-success" role="alert">
        <strong>Success:</strong>{{ Session::get('success') }}
    </div>
@endif

@if (count($errors)>0)
    <div class="alert alert-danger" role="alert">
        <strong>Error(s):</strong>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>

    </div>
@endif

resources/views/partials/_nav.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> <h3>TAILORED</h3> </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                <li><a href="/"><span class="fa fa-home fa-2x"></span> Home</a></li>
            @if(Auth::check())
                <li><a href="{{ route('purchases.create') }}" style="margin-top:8px">Create Your Order</a></li>
                <li> <a href="#"></a> </li>
                <!--<li class="dropdown">
                               <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                                  role="button" aria-expanded="false">
                                   <i class="fa fa-globe fa-2x" aria-hidden="true"></i>
                                   <span class="badge"
                                         style="background:gray; position: relative; top: -15px; left:-10px">
                                {{App\Notification::where('status', 1)
                                    ->where('followed', Auth::user()->id)
                                    ->count()}}
                                   </span>
                               </a>
                                  <?php
                                  $messages = DB::table('users')
                                       ->leftJoin('notifications', 'users.id', 'notifications.follower')
                                       ->where('followed', Auth::user()->id)
                                       //->where('status', 1) //unread message
                                       ->orderBy('notifications.created_at', 'desc')
                                       ->get();
                                  ?>

                                  <ul class="dropdown-menu" role="menu">
                                      @foreach($messages as $message)
                                         <a href="{{url('/notifications')}}/{{$message->id}}">
                                           @if($message->status==1)
                                       <li style="background:#E4E9F2; padding:10px">
                                         @else
                                         <li style="padding:10px">
                                           @endif
                                        <div class="row">
                                         <div class="col-md-2">
                                           <img src="{{Storage::url($message->img) }}"
                                            style="width:50px; padding:5px; background:#fff; border:1px solid #eee" class="img-rounded">
                                         </div>

                                       <div class="col-md-10">

                                        <b style="color:green; font-size:90%">{{ucwords($message->name)}}</b>
                                         <span style="color:#000; font-size:90%">{{$message->message}}</span>
                                         <br/>
                                         <small style="color:#90949C"> <i aria-hidden="true"></i>
                                           {{date('F j, Y', strtotime($message->created_at))}}
                                         at {{date('H: i', strtotime($message->created_at))}}</small>
                                       </div>

                                       </div>
                                       </li></a>
                                      @endforeach
                                  </ul>
                              </li>-->
            @endif
                <li class="dropdown" style="margin-top:8px"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                     aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
                    <?php
                    use App\Category;
                    $categories=Category::all();
                    ?>
                    <ul class="dropdown-menu">
                        @foreach ($categories as $category)
                            <li><a href="{{ route('categories.show',$category->id) }}">
                                {{ $category->name }}
                            </a>
                            </li>
                        @endforeach

                    </ul>
                    </li>
                </ul>
                @if (Auth::check())

            <ul class="nav navbar-nav navbar-right">
                <li class="{{ Request::is('shopping-cart')? "active":"" }}"><a href="{{ route('products.shoppingCart') }}">
                    <span class="fa fa-shopping-cart fa-2x"></span> Cart <span class="badge">{{ Session::has('cart')? Session::get('cart')->
                totalQty:'' }}</span></a></li>

                <li class="dropdown">
                    <?php
                    $user=Auth::user();
                    ?>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span><img src="{{Storage::url($user->img) }}" width="30px" height="30px" class="img-rounded"></span>
                        <span>{{ Auth::user()->username }} </span><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        @if (Auth::id()==$user->id)
                            <li><a href="{{ url('profile',['slug'=>Auth::user()->slug]) }}">Profile</a></li>
                        @endif
                        <!--<li><a href="{{ url('/findFriends') }}">Find User</a></li>-->
                        <li role="separator" class="divider"></li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
                @else
                    <div style="margin-top:7px">
                        <a href="{{ route('register') }}" class="pull-right btn btn-primary btn-sm">Sign Up</a>
                        <a href="{{ route('login') }}" class="pull-right btn btn-info btn-sm">Login</a>
                    </div>
            @endif
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-->
</nav>

resources/views/partials/_scripts.blade.php
<script src="{{asset('js/jquery-3.2.1.min.js')}}"></script>
<script src="{{asset('js/SmoothScroll.min.js')}}"></script>
<script type="text/javascript" src="{{asset('js/move-top.js')}}"></script>
<script type="text/javascript" src="{{asset('js/easing.js')}}"></script>
<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){
					event.preventDefault();

			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
				});
			});
</script>
<script type="text/javascript">
		$(document).ready(function() {
			/*
			var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
			};
			*/

			$().UItoTop({ easingType: 'easeOutQuart' });

		});
	</script>
    <script src="{{asset('js/app.js')}}"></script>