routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//cart
Route::get('add_to_cart/{id}',['uses'=>'ProductController@getAddToCart','as'=>'products.addToCart']);
Route::get('Padd_to_cart/{id}',['uses'=>'PurchaseController@getAddToCart','as'=>'purchase.addToCart']);
Route::get('shopping-cart',['uses'=>'ProductController@getCart','as'=>'products.shoppingCart']);
Route::get('/','PagesController@getIndex');
Route::get('showDesign', 'PagesController@showDesign');
Route::get('/reduce/{id}', ['uses' => 'ProductController@getReduceByOne','as' => 'product.reduceByOne']);
Route::get('/remove/{id}', ['uses' => 'ProductController@getRemoveItem','as' => 'product.remove']);
Route::get('empty','ProductController@empty')->name('clearCart');

Route::group(['middleware'=>['web','auth']],function(){
    //checkout
    Route::get('checkout',['uses'=>'ProductController@getCheckout', 'as'=>'checkout']);
    Route::post('checkout',['uses'=>'ProductController@postCheckout', 'as'=>'checkout']);
    //Pages Controller
    Route::get('contact', 'PagesController@getContact');
    Route::post('contact', 'PagesController@postContact');

    //resource controllers
    Route::resource('purchases','PurchaseController',['except'=>['edit','update']]);
    Route::resource('designs','DesignController',['except'=>['create','index','edit','update','show']]);
    Route::resource('products', 'ProductController',['except'=>['edit','update']]);
    Route::resource('categories', 'CategoryController');

    //ProfileController
    Route::get('/profile/{slug}','ProfileController@index')->name('profile.index');
    Route::get('/profile/edit/profile','ProfileController@edit')->name('profile.edit');
    Route::post('/profile/update','ProfileController@update')->name('profile.update');
    Route::get('/changeImage','ProfileController@changeImage');
    Route::post('/uploadImage','ProfileController@uploadImage');

    Route::get('/findFriends', 'ProfileController@findFriends');
    Route::get('/addFriend/{id}', 'ProfileController@sendRequest');
    Route::get('/followers', 'ProfileController@followers');
    Route::get('/unfollow/{id}', 'ProfileController@unfollow');
    Route::get('/notifications/{id}', 'ProfileController@notifications');

    //Route::get('/accept/{name}/{id}', 'ProfileController@accept');

    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
});

Auth::routes();

Route::get('/welcome', 'PagesController@getIndex')->name('welcome');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table='categories';

    public function products(){

        return $this->hasMany('App\Product');
    }
    public function designs(){

        return $this->hasMany('App\Design');
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Session;
use App\Category;
use App\Product;

class CategoryController extends Controller
{
    public function _construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $categories=Category::all();
        return view('categories.index')->withCategories($categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required|max:255',
        ]);
        $category=new Category;

        $category->name=$request->name;

        $category->save();

        Session::flash('success', 'Category Saved');
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $products=Category::find($id)->products;

        $categories=Category::all();
        return view('categories.index')->withCategories($categories)->withProducts($products);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/categories/create.blade.php
@extends('main')

@section('title','| Create New Category')

@section('content')

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form class="form-group" action="{{ route('categories.store') }}" method="post" data-app-validate="">
                {{ csrf_field() }}
                <h2>New Category</h2>
                {{ Form::label('name','Name:') }}
                {{ Form::text('name',null,['class'=>'form-control', 'required'=>'']) }}

                {{ Form::submit('Create Category',['class'=>'btn btn-success btn-block', 'style'=>'margin-top:10px']) }}
            </form>
        </div>
    </div>

@endsection

resources/views/categories/index.blade.php
@extends('main')

@section('title', '| Categories')

@section('content')
<div class="">
    <div class="col-md-12">
        <div class="navbar">
            <h3>Categories</h3>
            <ul class="nav navbar-nav">
                @if(!empty($categories))
                    @forelse ($categories as $category)
                        <li>
                            <a href="{{ route('categories.show',$category->id) }}">{{$category->name}}</a>
                        </li>
                    @empty
                        <li>No data</li>
                    @endforelse
                @endif
            </ul>
        </div>
            @if(!empty($products))
        <section>
            <h2>Products</h2>
                <div class="">
                    <div class="col-md-12">
                        @forelse ($products as $product)
                                <div class="col-md-4 thumbnail">
                                    <div class="">
                                        <img style="width:300px,height:450px" src="{{ url('../') }}/storage/image/{{ $product->image }}" alt="">
                                    </div>
                                    <div>
                                        <h3>{{ $product->name }}</h3>
                                    </div>
                                    <div>
                                        <p>{{ $product->description }}</p>
                                    </div>
                                    <div class="clearfix">
                                        <a href="{{ route('products.addToCart',$product->id) }}" class="btn btn-xs btn-success pull-right">Add To Cart</a>
                                    </div>
                                </div>
                            @empty
                                <tr>
                                    <td>No Product Available in this Category</td>
                                </tr>
                            @endforelse
                        </div>
                   </div>
                </div>
            @endif
        </section>
    </div>
</div>
@endsection