routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//cart
Route::get('add_to_cart/{id}',['uses'=>'ProductController@getAddToCart','as'=>'products.addToCart']);
Route::get('Padd_to_cart/{id}',['uses'=>'PurchaseController@getAddToCart','as'=>'purchase.addToCart']);
Route::get('shopping-cart',['uses'=>'ProductController@getCart','as'=>'products.shoppingCart']);
Route::get('/','PagesController@getIndex');
Route::get('showDesign', 'PagesController@showDesign');
Route::get('/reduce/{id}', ['uses' => 'ProductController@getReduceByOne','as' => 'product.reduceByOne']);
Route::get('/remove/{id}', ['uses' => 'ProductController@getRemoveItem','as' => 'product.remove']);
Route::get('empty','ProductController@empty')->name('clearCart');

Route::group(['middleware'=>['web','auth']],function(){
    //checkout
    Route::get('checkout',['uses'=>'ProductController@getCheckout', 'as'=>'checkout']);
    Route::post('checkout',['uses'=>'ProductController@postCheckout', 'as'=>'checkout']);
    //Pages Controller
    Route::get('contact', 'PagesController@getContact');
    Route::post('contact', 'PagesController@postContact');

    //resource controllers
    Route::resource('purchases','PurchaseController',['except'=>['edit','update']]);
    Route::resource('designs','DesignController',['except'=>['create','index','edit','update','show']]);
    Route::resource('products', 'ProductController',['except'=>['edit','update']]);
    Route::resource('categories', 'CategoryController');

    //ProfileController
    Route::get('/profile/{slug}','ProfileController@index')->name('profile.index');
    Route::get('/profile/edit/profile','ProfileController@edit')->name('profile.edit');
    Route::post('/profile/update','ProfileController@update')->name('profile.update');
    Route::get('/changeImage','ProfileController@changeImage');
    Route::post('/uploadImage','ProfileController@uploadImage');

    Route::get('/findFriends', 'ProfileController@findFriends');
    Route::get('/addFriend/{id}', 'ProfileController@sendRequest');
    Route::get('/followers', 'ProfileController@followers');
    Route::get('/unfollow/{id}', 'ProfileController@unfollow');
    Route::get('/notifications/{id}', 'ProfileController@notifications');

    //Route::get('/accept/{name}/{id}', 'ProfileController@accept');

    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
});

Auth::routes();

Route::get('/welcome', 'PagesController@getIndex')->name('welcome');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable=['user_id','name','price','description','category_id','image'];
    public function category(){

        return $this->belongsTo('App\Category');
    }
    public function user()
    {
       return $this->belongsTo('App\User');
     }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use Session;
use App\Profile;
use Auth;
use App\Category;
use App\Cart;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $products=Product::orderBy('created_at', 'desc')->limit(8)->get();
        return view('products.index')->withProducts($products);
    }

    Public function getAddToCart(Request $request,$id)//add product to cart
    {
            $product=Product::find($id);
            $oldCart=Session::has('cart') ? Session::get('cart') : null;
            $cart=new Cart($oldCart);
            $cart->add($product,$product->id);

            $request->session()->put('cart',$cart);

            return redirect()->route('products.index');
    }
    public function getReduceByOne($id) {
        $oldCart = Session::has('cart') ? Session::get('cart') : null;
        $cart = new Cart($oldCart);
        $cart->reduceByOne($id);

        if (count($cart->items) > 0) {
            Session::put('cart', $cart);
        } else {
            Session::forget('cart');
        }
        return redirect()->route('products.shoppingCart');
    }

    public function getRemoveItem($id) {
        $oldCart = Session::has('cart') ? Session::get('cart') : null;
        $cart = new Cart($oldCart);
        $cart->removeItem($id);

        if (count($cart->items) > 0) {
            Session::put('cart', $cart);
        } else {
            Session::forget('cart');
        }

        return redirect()->route('products.shoppingCart');
    }
    public function getCart()//return Cart view
    {
        $products = Product::all();
        if(Session::has('cart')){
            return view('shop.shopping-cart')->withProducts($products);
        }
        $oldCart= Session::get('cart');
        $cart =new Cart($oldCart);
        $totalPrice = $cart->totalPrice;


        return view('shop.shopping-cart',['products'=>$cart->items]);
    }
    public function empty()
    {
        if(Session::has('cart')){

        Session::forget('cart');
    }

        return back();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::all();
        return view('products.create')->withCategories($categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required',
            'description'=>'required|min:5|max:1000',
            'category_id'=>'required|integer',
            'price'=>'required',
            'image'=>'required|max:1990'
        ]);
        if($request->hasFile('image')){
            $filenameWithExt = $request->file('image')->getClientOriginalName();
            $filename=pathinfo($filenameWithExt,PATHINFO_FILENAME);
            $extension = $request->file('image')->getClientOriginalExtension();
            $fileNameToStore = $filename.'.'.time().'.'.$extension;
            $path = $request->file('image')->storeAs('public/image', $fileNameToStore);
        }else{
            $fileNameToStore = noimage.jpg;
        }



        $product=new Product;

        $product->name=$request->name;
        $product->image=$fileNameToStore;
        $product->description=$request->description;
        $product->category_id=$request->category_id;
        $product->price=$request->price;

        Auth::user()->product()->save($product);

        Session::flash('success','Saved');
        return redirect()->route('products.show', $product->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product=Product::find($id);
        return view('products.show')->withProduct($product);
    }

    public function destroy($id)
    {
        $product=Product::find($id);

        $product->delete();

        Session::flash('success', 'Deleted');
        return redirect()->route('products.index');

    }
    public function getCheckout(){
        if (Session::has('cart')){
            $oldCart = Session::get('cart');
            $cart= new Cart($oldCart);
            $total = $cart->totalPrice;

            return view('shop.checkout')->withTotal($total);
        }
    }
}

resources/views/products/create.blade.php
@extends('main')

@section('title', 'Create Product')

@section('content')

    <h2 align="center" style="margin-top:20px">Add Product</h2>
    <hr>
    <div class="container">
        <div class="col-md-10 col-md-offset-1">
            <div class="col-md-6 col-md-offset-2 thumbnail">
                <form action="{{route('products.store')}}" method="POST" data-app-validate="" enctype="multipart/form-data">
                    {{ csrf_field() }}

                    {{ Form::label('image', 'Product Image') }}
                    {{ Form::file('image',null,['class'=>'form-control','required'=>'']) }}

                    {{ Form::label('name', 'Product:') }}
                    {{ Form::text('name',null,['class'=>'form-control','required'=>'']) }}

                    {{ Form::label('category_id','Category:') }}
                    <select class="form-control" name="category_id">
                        @foreach ($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>

                    {{ Form::label('description','Description:') }}
                    {{ Form::textarea('description',null,['class'=>'form-control', 'rows'=>'2','required'=>'']) }}


                    {{ Form::label('price','Price') }}
                    {{ Form::text('price',null,['class'=>'form-control','required'=>'']) }}
                        <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/products/index.blade.php
@extends('main')

@section('title','| Available Products')

@section('content')
   <div class="row">
        <div class="col-md-10">
            <h1>All Products</h1>
        </div>
@if (Auth::user()->account_type == 'designer')
    <div class="col-md-2">
        <a href="{{ route('products.create') }}" class="btn btn-primary">Post New Product</a>
    </div>
@endif
        <div class="col-md-12">
            <hr>
        </div>
    </div>
    <div class="">
        <div class="col-md-12">
            <div class="gallery">
        		<div class="container">
        			<h3 class="agileits-title">Shop</h3>
        			<div class="gallery-agileinfo">
                    @forelse ($products as $product)
        				<div class="col-md-4 col-xs-6 w3gallery-grids">
        					<a href="{{ url('../') }}/storage/image/{{ $product->image }}" class="imghvr-hinge-right figure">
        						<img height="450px" width="300px" style="border-redius:50%" src="{{ url('../') }}/storage/image/{{ $product->image }}" alt="" title="New Designs Image"/>
        						<div class="agile-figcaption">
        						  <h4>{{ $product->name }}</h4>
        						  <p>{{ $product->description }}</p>
        						  <p>By:{{ $product->user->profile->brand }}</p>
        						</div>
                                <div class="">
                                    <a href="{{ route('products.addToCart',['id'=>$product->id]) }}" class="btn btn-primary btn-sm">Add To Cart</a>
                                </div>
        					</a>
        				</div>
                    @empty
                        <div class="col-md-12">
                            <h3 align="center"><strong>This Shop Is Empty</strong></h3>
                        </div>
                    @endforelse
        				<div class="clearfix"> </div>
        				<script type="text/javascript" src="{{asset('js/simple-lightbox.min.js')}}"></script>
        				<script>
        					$(function(){
        						var gallery = $('.w3gallery-grids a').simpleLightbox({navText:		['&lsaquo;','&rsaquo;']});
        					});
        				</script>
        			</div>
        		</div>
        	</div>
        </div>
    </div>

@endsection

resources/views/products/show.blade.php
@extends('main')

@section('title','Details')

@section('content')

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="col-md-6 col-md-offset-3 thumbnail">
            <div class="">
                <img heght="250px" width="100px" style="width:100%" src="/storage/image/{{ $product->image }}" alt="">
            </div>
            <div>
                <h3>{{ $product->name }}</h3>
            </div>
            <div>
                <p>{{ $product->description }}</p>
            </div>
            <div>
                <p>#{{ $product->price }}</p>
            </div>
            <div class="col-sm-6">
                {!! Form::open(['route'=>['products.destroy',$product->id], 'method'=>'DELETE']) !!}

                {!! Form::submit('Delete', ['class'=>'btn btn-danger btn-block']) !!}

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>


@endsection